spring:
  profiles: local
influxdb:
  url: http://localhost:8086
  username: admin
  database: pc2DataTest
  retention-policy: pc2
lap-tracker:
  file-name: lap-tracker.json
management:
  endpoints:
    web:
      exposure:
        include: health,httptrace,info,loggers,mappings
---

spring:
  profiles: test
influxdb:
  url: http://localhost:8086
  username:
  database: pc2DataTest
  retention-policy: autogen
lap-tracker:
  file-name: lap-tracker.json

---

spring:
  profiles: production
influxdb:
  url: http://localhost:8086
  database: pc2DataProd
  retention-policy: forever
lap-tracker:
  file-name: lap-tracker.json

