package com.jack_watson.enums

enum class FlagColor(val num: Int) {
    FLAG_COLOR_NONE(0),
    FLAG_COLOR_GREEN(1),
    FLAG_COLOR_BLUE(2),
    FLAG_COLOR_WHITE_SLOW_CAR(3),
    FLAG_COLOR_WHITE_FINAL_LAP(4),
    FLAG_COLOR_RED(5),
    FLAG_COLOR_YELLOW(6),
    FLAG_COLOR_DOUBLE_YELLOW(7),
    FLAG_COLOR_BLACK_AND_WHITE(8),
    FLAG_COLOR_BLACK_ORANGE_CIRCLE(9),
    FLAG_COLOR_BLACK(10),
    FLAG_COLOR_CHECKERED(11),
    FLAG_COLOR_MAX(12)
}