package com.jack_watson.enums

enum class PitSchedule (val num: Int) {
    PIT_SCHEDULE_NONE(0),
    PIT_SCHEDULE_PLAYER_REQUESTED(1),
    PIT_SCHEDULE_ENGINEER_REQUESTED(2),
    PIT_SCHEDULE_DAMAGE_REQUESTED(3),
    PIT_SCHEDULE_MANDATORY(4),
    PIT_SCHEDULE_DRIVE_THROUGH(5),
    PIT_SCHEDULE_STOP_GO(6),
    PIT_SCHEDULE_PITSPOT_OCCUPIED(7),
    PIT_SCHEDULE_MAX(8),
}